# Generated by Django 4.0.2 on 2022-05-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_teacher_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='file',
        ),
    ]
